"""add missing inventory item fields

Revision ID: 0d3f50f53fbe
Revises: bd0a62a88784
Create Date: 2026-03-28 14:57:21.741813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3f50f53fbe'
down_revision = 'bd0a62a88784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_stock', sa.Numeric(precision=12, scale=3), nullable=True))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('barcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'restaurant_orders', ['parent_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('barcode')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('target_stock')

    # ### end Alembic commands ###
