"""add description to rooms

Revision ID: 8e62f8423756
Revises: c5fa9138681c
Create Date: 2026-02-16 04:08:43.903594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e62f8423756'
down_revision = 'c5fa9138681c'
branch_labels = None
depends_on = None


def upgrade():
    # Add description column to rooms table
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('check_out_time',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('check_in_time',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('cover_image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('favicon_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
