"""Add soft delete deleted_at to Invoice Payment JournalEntry JournalLine

Revision ID: 91614cba09e1
Revises: 9f8d63e916ee
Create Date: 2026-02-15 04:10:21.970988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91614cba09e1'
down_revision = '9f8d63e916ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
