"""add_missing_restaurant_order_columns

Revision ID: 9cd8334fbff6
Revises: bef10a7aecb5
Create Date: 2026-02-21 08:31:16.714962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cd8334fbff6'
down_revision = 'bef10a7aecb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_reference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_bookings_check_in'))
        batch_op.drop_index(batch_op.f('ix_bookings_check_out'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_at'))
        batch_op.drop_index(batch_op.f('ix_bookings_guest_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_reference'))
        batch_op.drop_index(batch_op.f('ix_bookings_room_dates'))
        batch_op.drop_index(batch_op.f('ix_bookings_room_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_chart_of_accounts_type'))

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_guests_email'))
        batch_op.drop_index(batch_op.f('ix_guests_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_guests_name'))
        batch_op.drop_index(batch_op.f('ix_guests_phone'))

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotels_name'))
        batch_op.drop_index(batch_op.f('ix_hotels_owner_id'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_booking_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.create_unique_constraint(None, ['invoice_number'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_hotel_id'))

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_entry_id'))

    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_categories_hotel_id'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('menu_item_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('menu_item_inventory_menu_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu_items', ['menu_item_id'], ['id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_is_available'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('purchase_orders_journal_entry_id_fkey'), type_='foreignkey')
        batch_op.drop_column('journal_entry_id')

    with op.batch_alter_table('restaurant_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_order_items_order_id'))

    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_restaurant_orders_status'))
        batch_op.drop_index(batch_op.f('ix_restaurant_orders_table_id'))
        batch_op.create_foreign_key(None, 'users', ['server_id'], ['id'])

    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurant_tables_hotel_id'))
        batch_op.drop_column('shape')

    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_types_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_room_types_name'))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_room_number'))
        batch_op.drop_index(batch_op.f('ix_rooms_room_type_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_status'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stock_movements_journal_entry_id_fkey'), type_='foreignkey')
        batch_op.drop_column('journal_entry_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_users_last_login_at'))
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_login_at'), ['last_login_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('stock_movements_journal_entry_id_fkey'), 'journal_entries', ['journal_entry_id'], ['id'])

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_room_type_id'), ['room_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_room_number'), ['room_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_hotel_id'), ['hotel_id'], unique=False)

    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_types_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_types_hotel_id'), ['hotel_id'], unique=False)

    with op.batch_alter_table('restaurant_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shape', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_restaurant_tables_hotel_id'), ['hotel_id'], unique=False)

    with op.batch_alter_table('restaurant_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_restaurant_orders_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurant_orders_status'), ['status'], unique=False)
        batch_op.drop_column('balance_due')
        batch_op.drop_column('tip_amount')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('server_id')

    with op.batch_alter_table('restaurant_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurant_order_items_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('purchase_orders_journal_entry_id_fkey'), 'journal_entries', ['journal_entry_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('booking_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_menu_items_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('menu_item_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('menu_item_inventory_menu_item_id_fkey'), 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('menu_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_menu_categories_hotel_id'), ['hotel_id'], unique=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_date'), ['date'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotels_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotels_name'), ['name'], unique=False)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_email'), ['email'], unique=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('chart_of_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_accounts_hotel_id'), ['hotel_id'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_room_dates'), ['room_id', 'check_in_date', 'check_out_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_reference'), ['booking_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_check_out'), ['check_out_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_check_in'), ['check_in_date'], unique=False)
        batch_op.alter_column('booking_reference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('guest_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
