"""Add hotel branding fields

Revision ID: add_hotel_branding_fields
Revises: c1f2a3b4c5d6
Create Date: 2026-02-15 15:06:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_hotel_branding_fields'
down_revision = 'c1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to hotels table
    op.add_column('hotels', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('favicon_url', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('cover_image_url', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('website_url', sa.String(length=200), nullable=True))
    op.add_column('hotels', sa.Column('facebook_url', sa.String(length=200), nullable=True))
    op.add_column('hotels', sa.Column('instagram_url', sa.String(length=200), nullable=True))
    op.add_column('hotels', sa.Column('twitter_url', sa.String(length=200), nullable=True))
    op.add_column('hotels', sa.Column('tax_number', sa.String(length=50), nullable=True))
    op.add_column('hotels', sa.Column('registration_number', sa.String(length=50), nullable=True))
    op.add_column('hotels', sa.Column('email_header_color', sa.String(length=20), nullable=True))
    op.add_column('hotels', sa.Column('email_footer_text', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('email_logo_url', sa.String(length=500), nullable=True))
    op.add_column('hotels', sa.Column('cancellation_policy', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('children_policy', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('pet_policy', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('payment_policy', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove new columns from hotels table
    op.drop_column('hotels', 'payment_policy')
    op.drop_column('hotels', 'pet_policy')
    op.drop_column('hotels', 'children_policy')
    op.drop_column('hotels', 'cancellation_policy')
    op.drop_column('hotels', 'email_logo_url')
    op.drop_column('hotels', 'email_footer_text')
    op.drop_column('hotels', 'email_header_color')
    op.drop_column('hotels', 'registration_number')
    op.drop_column('hotels', 'tax_number')
    op.drop_column('hotels', 'twitter_url')
    op.drop_column('hotels', 'instagram_url')
    op.drop_column('hotels', 'facebook_url')
    op.drop_column('hotels', 'cover_image_url')
    op.drop_column('hotels', 'favicon_url')
    op.drop_column('hotels', 'display_name')
