"""add_gallery_images_table

Revision ID: d4e5f6a7b8c9
Revises: c72c71ed8974
Create Date: 2026-02-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e5f6a7b8c9'
down_revision = 'c72c71ed8974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('size_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better query performance
    op.create_index('idx_gallery_images_hotel_id', 'gallery_images', ['hotel_id'])
    op.create_index('idx_gallery_images_category', 'gallery_images', ['category'])
    op.create_index('idx_gallery_images_is_active', 'gallery_images', ['is_active'])
    op.create_index('idx_gallery_images_size_type', 'gallery_images', ['size_type'])
    op.create_index('idx_gallery_images_sort_order', 'gallery_images', ['sort_order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gallery_images_sort_order', table_name='gallery_images')
    op.drop_index('idx_gallery_images_size_type', table_name='gallery_images')
    op.drop_index('idx_gallery_images_is_active', table_name='gallery_images')
    op.drop_index('idx_gallery_images_category', table_name='gallery_images')
    op.drop_index('idx_gallery_images_hotel_id', table_name='gallery_images')
    op.drop_table('gallery_images')
    # ### end Alembic commands ###
